# Generated by Django 5.0.2 on 2025-11-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
