# Generated by Django 5.0.2 on 2025-11-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0004_alter_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
