# Generated by Django 5.0.2 on 2025-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0005_alter_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='update1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
