# Generated by Django 5.0.2 on 2025-11-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0006_maestros_update1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='update1',
        ),
    ]
