# Generated by Django 5.0.2 on 2025-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0007_remove_maestros_update1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
