# Generated by Django 5.0.2 on 2025-12-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0009_fix_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=3)),
                ('dias_json', models.JSONField(blank=True, default=dict)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_impartidas', to='app_escolar_api.maestros')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nrc'],
            },
        ),
    ]
